// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALksl6qc-ht2ArInPE2xA-q_7b7MgjwjU',
    appId: '1:449162847594:web:96365101b00730ac527113',
    messagingSenderId: '449162847594',
    projectId: 'urbanhomey-363dc',
    authDomain: 'urbanhomey-363dc.firebaseapp.com',
    storageBucket: 'urbanhomey-363dc.firebasestorage.app',
    measurementId: 'G-09Z250TQ76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADf9kgysGirNyfIBjtCGVtyVi0BGQW8oA',
    appId: '1:449162847594:android:8d9433cfccd17997527113',
    messagingSenderId: '449162847594',
    projectId: 'urbanhomey-363dc',
    storageBucket: 'urbanhomey-363dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsUaVu-ft6DVq50pAU2l6NY4deZOSUd0s',
    appId: '1:449162847594:ios:ea137a704dad6de1527113',
    messagingSenderId: '449162847594',
    projectId: 'urbanhomey-363dc',
    storageBucket: 'urbanhomey-363dc.firebasestorage.app',
    iosBundleId: 'com.urbanhomey.app',
  );

}